version: "3"
services:

  frontend:
    build:
      context: ./frontend
    volumes:
      - vue_build:/server/public
    ports:
      - "8080:8080"
    container_name: frontend_container

  backend:
    build:
      context: ./server
    volumes:
      - vue_build:/server/public
    ports:
      - "8000:8000"
    container_name: backend_container

  nginx:
    image: nginx:latest
    ports:
      - "7070:7070"
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - vue_build:/var/www/vue
    depends_on:
      - backend
      - frontend

volumes:
 vue_build:
