export const communities = [
  {
    communityId: 12345,
    name: "Community Name",
    description:
      " Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem",
    createdAt: "2021-02-24",
    members: 543,
    owner: "John Smith",
    photo: "https://cdn.vuetifyjs.com/images/cards/house.jpg",
  },
  {
    communityId: 67890,
    name: "ABC",
    description:
      " Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem",
    createdAt: "2021-02-24",
    members: 543,
    owner: "John Smith",
    photo: "https://cdn.vuetifyjs.com/images/cards/house.jpg",
  },
  {
    communityId: 12345,
    name: "CDE",
    description:
      " Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem",
    createdAt: "2021-02-24",
    members: 543,
    owner: "John Smith",
    photo: "https://cdn.vuetifyjs.com/images/cards/house.jpg",
  },
  {
    communityId: 12345,
    name: "DEF",
    description:
      " Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem",
    createdAt: "2021-02-24",
    members: 543,
    owner: "John Smith",
    photo: "https://cdn.vuetifyjs.com/images/cards/house.jpg",
  },
  {
    communityId: 12345,
    name: "Community Name",
    description:
      " Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem",
    createdAt: "2021-02-24",
    members: 543,
    owner: "John Smith",
    photo: "https://cdn.vuetifyjs.com/images/cards/house.jpg",
  },
  {
    communityId: 12345,
    name: "Community Name",
    description:
      " Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem",
    createdAt: "2021-02-24",
    members: 543,
    owner: "John Smith",
    photo: "https://cdn.vuetifyjs.com/images/cards/house.jpg",
  },
  {
    communityId: 12345,
    name: "Community Name",
    description:
      " Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem",
    createdAt: "2021-02-24",
    members: 543,
    owner: "John Smith",
    photo: "https://cdn.vuetifyjs.com/images/cards/house.jpg",
  },
  {
    communityId: 12345,
    name: "Community Name",
    description:
      " Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem",
    createdAt: "2021-02-24",
    members: 543,
    owner: "John Smith",
    photo: "https://cdn.vuetifyjs.com/images/cards/house.jpg",
  },
  {
    communityId: 12345,
    name: "Community Name",
    description:
      " Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem",
    createdAt: "2021-02-24",
    members: 543,
    owner: "John Smith",
    photo: "https://cdn.vuetifyjs.com/images/cards/house.jpg",
  },
  {
    communityId: 67890,
    name: "ABC",
    description:
      " Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem",
    createdAt: "2021-02-24",
    members: 543,
    owner: "John Smith",
    photo: "https://cdn.vuetifyjs.com/images/cards/house.jpg",
  },
  {
    communityId: 12345,
    name: "CDE",
    description:
      " Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem",
    createdAt: "2021-02-24",
    members: 543,
    owner: "John Smith",
    photo: "https://cdn.vuetifyjs.com/images/cards/house.jpg",
  },
  {
    communityId: 12345,
    name: "DEF",
    description:
      " Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem",
    createdAt: "2021-02-24",
    members: 543,
    owner: "John Smith",
    photo: "https://cdn.vuetifyjs.com/images/cards/house.jpg",
  },
  {
    communityId: 12345,
    name: "Community Name",
    description:
      " Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem",
    createdAt: "2021-02-24",
    members: 543,
    owner: "John Smith",
    photo: "https://cdn.vuetifyjs.com/images/cards/house.jpg",
  },
  {
    communityId: 67890,
    name: "ABC",
    description:
      " Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem",
    createdAt: "2021-02-24",
    members: 543,
    owner: "John Smith",
    photo: "https://cdn.vuetifyjs.com/images/cards/house.jpg",
  },
  {
    communityId: 12345,
    name: "CDE",
    description:
      " Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem",
    createdAt: "2021-02-24",
    members: 543,
    owner: "John Smith",
    photo: "https://cdn.vuetifyjs.com/images/cards/house.jpg",
  },
  {
    communityId: 12345,
    name: "DEF",
    description:
      " Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem",
    createdAt: "2021-02-24",
    members: 543,
    owner: "John Smith",
    photo: "https://cdn.vuetifyjs.com/images/cards/house.jpg",
  },
];

export const notes = [
  {
    noteId: 1234,
    noteTitle: "Note Title",
    dataUrl: "https://www.google.com",
    createdAt: "2021-02-23",
    likeCount: 12,
    viewCount: 45,
    commentCount: 56,
    owner: "Brian Yin",
    ownerId: 104,
    categories: ["Computer Science"],
  },
  {
    noteId: 1234,
    noteTitle: "Note Title",
    dataUrl: "https://www.google.com",
    createdAt: "2021-02-23",
    likeCount: 12,
    viewCount: 45,
    commentCount: 56,
    owner: "Brian Yin",
    ownerId: 123,
    categories: ["Computer Science"],
  },
  {
    noteId: 1234,
    noteTitle: "Note Title",
    dataUrl: "https://www.google.com",
    createdAt: "2021-02-23",
    likeCount: 12,
    viewCount: 45,
    commentCount: 56,
    owner: "Brian Yin",
    ownerId: 123,
    categories: ["Computer Science"],
  },
  {
    noteId: 1234,
    noteTitle: "Note Title",
    dataUrl: "https://www.google.com",
    createdAt: "2021-02-23",
    likeCount: 12,
    viewCount: 45,
    commentCount: 56,
    owner: "Brian Yin",
    ownerId: 123,
    categories: ["Computer Science"],
  },
  {
    noteId: 1234,
    noteTitle: "Note Title",
    dataUrl: "https://www.google.com",
    createdAt: "2021-02-23",
    likeCount: 12,
    viewCount: 45,
    commentCount: 56,
    owner: "Brian Yin",
    ownerId: 123,
    categories: ["Computer Science"],
  },
  {
    noteId: 1234,
    noteTitle: "Note Title",
    dataUrl: "https://www.google.com",
    createdAt: "2021-02-23",
    likeCount: 12,
    viewCount: 45,
    commentCount: 56,
    owner: "Brian Yin",
    ownerId: 123,
    categories: ["Computer Science"],
  },
  {
    noteId: 1234,
    noteTitle: "Note Title",
    dataUrl: "https://www.google.com",
    createdAt: "2021-02-23",
    likeCount: 12,
    viewCount: 45,
    commentCount: 56,
    owner: "Brian Yin",
    ownerId: 123,
    categories: ["Computer Science"],
  },
  {
    noteId: 1234,
    noteTitle: "Note Title",
    dataUrl: "https://www.google.com",
    createdAt: "2021-02-23",
    likeCount: 12,
    viewCount: 45,
    commentCount: 56,
    owner: "Brian Yin",
    ownerId: 123,
    categories: ["Computer Science"],
  },
];

export const sharedUsers = [
  { ownerId: 104, name: "Brian Yin" },
  { ownerId: 102, name: "Boquan Yin" },
  { ownerId: 103, name: "Toubat Brian" },
  { ownerId: 105, name: "Lucheng Qing" },
];
