export const communities = [
  {
    communityId: 12345,
    name: "Community Name",
    description:
      " Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem",
    createdAt: "2021-02-24",
    members: 543,
    owner: "John Smith",
    photo: "https://cdn.vuetifyjs.com/images/cards/house.jpg",
  },
  {
    communityId: 67890,
    name: "ABC",
    description:
      " Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem",
    createdAt: "2021-02-24",
    members: 543,
    owner: "John Smith",
    photo: "https://cdn.vuetifyjs.com/images/cards/house.jpg",
  },
  {
    communityId: 12345,
    name: "CDE",
    description:
      " Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem",
    createdAt: "2021-02-24",
    members: 543,
    owner: "John Smith",
    photo: "https://cdn.vuetifyjs.com/images/cards/house.jpg",
  },
  {
    communityId: 12345,
    name: "DEF",
    description:
      " Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem",
    createdAt: "2021-02-24",
    members: 543,
    owner: "John Smith",
    photo: "https://cdn.vuetifyjs.com/images/cards/house.jpg",
  },
  {
    communityId: 12345,
    name: "Community Name",
    description:
      " Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem",
    createdAt: "2021-02-24",
    members: 543,
    owner: "John Smith",
    photo: "https://cdn.vuetifyjs.com/images/cards/house.jpg",
  },
  {
    communityId: 12345,
    name: "Community Name",
    description:
      " Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem",
    createdAt: "2021-02-24",
    members: 543,
    owner: "John Smith",
    photo: "https://cdn.vuetifyjs.com/images/cards/house.jpg",
  },
  {
    communityId: 12345,
    name: "Community Name",
    description:
      " Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem",
    createdAt: "2021-02-24",
    members: 543,
    owner: "John Smith",
    photo: "https://cdn.vuetifyjs.com/images/cards/house.jpg",
  },
  {
    communityId: 12345,
    name: "Community Name",
    description:
      " Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem",
    createdAt: "2021-02-24",
    members: 543,
    owner: "John Smith",
    photo: "https://cdn.vuetifyjs.com/images/cards/house.jpg",
  },
  {
    communityId: 12345,
    name: "Community Name",
    description:
      " Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem",
    createdAt: "2021-02-24",
    members: 543,
    owner: "John Smith",
    photo: "https://cdn.vuetifyjs.com/images/cards/house.jpg",
  },
  {
    communityId: 67890,
    name: "ABC",
    description:
      " Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem",
    createdAt: "2021-02-24",
    members: 543,
    owner: "John Smith",
    photo: "https://cdn.vuetifyjs.com/images/cards/house.jpg",
  },
  {
    communityId: 12345,
    name: "CDE",
    description:
      " Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem",
    createdAt: "2021-02-24",
    members: 543,
    owner: "John Smith",
    photo: "https://cdn.vuetifyjs.com/images/cards/house.jpg",
  },
  {
    communityId: 12345,
    name: "DEF",
    description:
      " Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem",
    createdAt: "2021-02-24",
    members: 543,
    owner: "John Smith",
    photo: "https://cdn.vuetifyjs.com/images/cards/house.jpg",
  },
  {
    communityId: 12345,
    name: "Community Name",
    description:
      " Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem",
    createdAt: "2021-02-24",
    members: 543,
    owner: "John Smith",
    photo: "https://cdn.vuetifyjs.com/images/cards/house.jpg",
  },
  {
    communityId: 67890,
    name: "ABC",
    description:
      " Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem",
    createdAt: "2021-02-24",
    members: 543,
    owner: "John Smith",
    photo: "https://cdn.vuetifyjs.com/images/cards/house.jpg",
  },
  {
    communityId: 12345,
    name: "CDE",
    description:
      " Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem",
    createdAt: "2021-02-24",
    members: 543,
    owner: "John Smith",
    photo: "https://cdn.vuetifyjs.com/images/cards/house.jpg",
  },
  {
    communityId: 12345,
    name: "DEF",
    description:
      " Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem Lorem ipsum dolor sit amet, consectetur adip Lorem ips Lorem",
    createdAt: "2021-02-24",
    members: 543,
    owner: "John Smith",
    photo: "https://cdn.vuetifyjs.com/images/cards/house.jpg",
  },
];

export const notes = [
  {
    noteId: 12,
    dataUrl: "https://www.google.com",
    noteTitle: "Note Title",
    createdAt: "2021-02-23",
    likeCount: 12,
    viewCount: 45,
    commentCount: 56,
    accessStatus: "owner",
    ownerId: 104,
    ownerName: "Brian Yin",
    sharedUsers: [
      {
        userId: 104,
        firstName: "Brian",
        lastName: "Yin",
        avatarUrl: null,
      },
      {
        userId: 102,
        firstName: "Toubat",
        lastName: "Brian",
        avatarUrl: null,
      },
      { userId: 103, firstName: "Lucheng", lastName: "Qing", avatarUrl: null },
      { userId: 105, firstName: "ABC", lastName: "DEF", avatarUrl: null },
    ],
    categories: ["Computer Science"],
  },
  {
    noteId: 27,
    dataUrl: "https://gnu.org",
    noteTitle: "Bloody Sunday",
    createdAt: "2020-10-22",
    likeCount: 1,
    viewCount: 33,
    commentCount: 33,
    accessStatus: "editor",
    ownerId: 104,
    ownerName: "Fons Whitehair",
    sharedUsers: [],
    categories: [],
  },
  {
    noteId: 24,
    dataUrl: "http://joomla.org",
    noteTitle: "Kinbaku",
    createdAt: "2020-10-29",
    likeCount: 12,
    viewCount: 70,
    commentCount: 15,
    accessStatus: "viewer",
    ownerId: 104,
    ownerName: "Danie Kayley",
    sharedUsers: [],
    categories: [],
  },
  {
    noteId: 28,
    dataUrl: "http://admin.ch",
    noteTitle: "No",
    createdAt: "2021-04-27",
    likeCount: 89,
    viewCount: 95,
    commentCount: 77,
    accessStatus: "owner",
    ownerId: 104,
    ownerName: "Mickie Fynan",
    sharedUsers: [
      {
        userId: 104,
        firstName: "Brian",
        lastName: "Yin",
        avatarUrl: null,
      },
      {
        userId: 102,
        firstName: "Toubat",
        lastName: "Brian",
        avatarUrl: null,
      },
      { userId: 103, firstName: "Lucheng", lastName: "Qing", avatarUrl: null },
      { userId: 105, firstName: "ABC", lastName: "DEF", avatarUrl: null },
    ],
    categories: [],
  },
  {
    noteId: 21,
    dataUrl: "https://netlog.com",
    noteTitle: "David and Lisa",
    createdAt: "2021-09-17",
    likeCount: 53,
    viewCount: 54,
    commentCount: 30,
    accessStatus: "editor",
    ownerId: 16,
    ownerName: "Yardley Cristoforetti",
    sharedUsers: [],
    categories: [],
  },
  {
    noteId: 5,
    dataUrl: "http://networkadvertising.org",
    noteTitle: "Trinity: Gambling for High Stakes (Odds and Evens) (Pari e dispari)",
    createdAt: "2021-09-05",
    likeCount: 44,
    viewCount: 93,
    commentCount: 93,
    accessStatus: "viewer",
    ownerId: 12,
    ownerName: "Kermit Brickell",
    sharedUsers: [],
    categories: [],
  },
  {
    noteId: 21,
    dataUrl: "http://army.mil",
    noteTitle: "Devil's Rain, The",
    createdAt: "2021-07-23",
    likeCount: 48,
    viewCount: 85,
    commentCount: 83,
    accessStatus: "owner",
    ownerId: 27,
    ownerName: "Ava Omar",
    sharedUsers: [
      {
        userId: 104,
        firstName: "Brian",
        lastName: "Yin",
        avatarUrl: null,
      },
      {
        userId: 102,
        firstName: "Toubat",
        lastName: "Brian",
        avatarUrl: null,
      },
      { userId: 103, firstName: "Lucheng", lastName: "Qing", avatarUrl: null },
      { userId: 105, firstName: "ABC", lastName: "DEF", avatarUrl: null },
    ],
    categories: [],
  },
  {
    noteId: 2,
    dataUrl: "http://msu.edu",
    noteTitle: "Ugly Duckling and Me!, The",
    createdAt: "2020-10-14",
    likeCount: 99,
    viewCount: 3,
    commentCount: 52,
    accessStatus: "editor",
    ownerId: 12,
    ownerName: "Rosabella Cops",
    sharedUsers: [],
    categories: [],
  },
  {
    noteId: 6,
    dataUrl: "http://google.es",
    noteTitle: "Hero",
    createdAt: "2020-12-14",
    likeCount: 18,
    viewCount: 62,
    commentCount: 71,
    accessStatus: "viewer",
    ownerId: 14,
    ownerName: "Ardenia Patsall",
    sharedUsers: [],
    categories: [],
  },
  {
    noteId: 20,
    dataUrl: "https://ovh.net",
    noteTitle: "Un vampiro para dos",
    createdAt: "2021-06-04",
    likeCount: 45,
    viewCount: 25,
    commentCount: 29,
    accessStatus: "owner",
    ownerId: 104,
    ownerName: "Gabey Emm",
    sharedUsers: [
      {
        userId: 104,
        firstName: "Brian",
        lastName: "Yin",
        avatarUrl: null,
      },
      {
        userId: 102,
        firstName: "Toubat",
        lastName: "Brian",
        avatarUrl: null,
      },
      { userId: 103, firstName: "Lucheng", lastName: "Qing", avatarUrl: null },
      { userId: 105, firstName: "ABC", lastName: "DEF", avatarUrl: null },
    ],
    categories: [],
  },
  {
    noteId: 9,
    dataUrl: "https://wordpress.org",
    noteTitle: "Down with Love",
    createdAt: "2020-11-12",
    likeCount: 20,
    viewCount: 50,
    commentCount: 28,
    accessStatus: "editor",
    ownerId: 3,
    ownerName: "Lydie Baunton",
    sharedUsers: [],
    categories: [],
  },
  {
    noteId: 8,
    dataUrl: "https://mashable.com",
    noteTitle: "Snatch",
    createdAt: "2020-10-27",
    likeCount: 13,
    viewCount: 4,
    commentCount: 32,
    accessStatus: "viewer",
    ownerId: 8,
    ownerName: "Kristyn Delatour",
    sharedUsers: [],
    categories: [],
  },
  {
    noteId: 29,
    dataUrl: "https://imdb.com",
    noteTitle: "Born to Defense (Zhong hua ying xiong)",
    createdAt: "2021-08-05",
    likeCount: 50,
    viewCount: 20,
    commentCount: 48,
    accessStatus: "owner",
    ownerId: 104,
    ownerName: "Kissiah MacGoun",
    sharedUsers: [],
    categories: [],
  },
  {
    noteId: 17,
    dataUrl: "https://fema.gov",
    noteTitle: "Courtship of Eddie's Father, The",
    createdAt: "2021-08-27",
    likeCount: 94,
    viewCount: 59,
    commentCount: 85,
    accessStatus: "editor",
    ownerId: 8,
    ownerName: "Gardiner Chatband",
    sharedUsers: [],
    categories: [],
  },
  {
    noteId: 1,
    dataUrl: "http://cnet.com",
    noteTitle: "Forget Me Not",
    createdAt: "2021-07-05",
    likeCount: 7,
    viewCount: 41,
    commentCount: 67,
    accessStatus: "viewer",
    ownerId: 9,
    ownerName: "Helaine Crowley",
    sharedUsers: [],
    categories: [],
  },
  {
    noteId: 2,
    dataUrl: "http://springer.com",
    noteTitle: "Cabin Fever: Patient Zero",
    createdAt: "2021-08-28",
    likeCount: 34,
    viewCount: 68,
    commentCount: 97,
    accessStatus: "owner",
    ownerId: 104,
    ownerName: "Hayley Ghidoli",
    sharedUsers: [],
    categories: [],
  },
  {
    noteId: 22,
    dataUrl: "https://mac.com",
    noteTitle: "Last Will of Dr. Mabuse, The (Testament du Dr. Mabuse, Le)",
    createdAt: "2021-02-22",
    likeCount: 67,
    viewCount: 91,
    commentCount: 27,
    accessStatus: "editor",
    ownerId: 19,
    ownerName: "Fina Henmarsh",
    sharedUsers: [],
    categories: [],
  },
  {
    noteId: 20,
    dataUrl: "https://ow.ly",
    noteTitle: "Dancemaker",
    createdAt: "2021-03-19",
    likeCount: 36,
    viewCount: 5,
    commentCount: 56,
    accessStatus: "viewer",
    ownerId: 14,
    ownerName: "Merralee Sieb",
    sharedUsers: [],
    categories: [],
  },
  {
    noteId: 19,
    dataUrl: "http://com.com",
    noteTitle: "Secret Adventures of Tom Thumb, The",
    createdAt: "2020-09-06",
    likeCount: 88,
    viewCount: 40,
    commentCount: 92,
    accessStatus: "owner",
    ownerId: 104,
    ownerName: "Ardath Josefowicz",
    sharedUsers: [],
    categories: [],
  },
  {
    noteId: 0,
    dataUrl: "http://japanpost.jp",
    noteTitle: "Margaret",
    createdAt: "2020-11-02",
    likeCount: 56,
    viewCount: 57,
    commentCount: 35,
    accessStatus: "editor",
    ownerId: 7,
    ownerName: "Marris Hiddsley",
    sharedUsers: [],
    categories: [],
  },
  {
    noteId: 20,
    dataUrl: "http://skype.com",
    noteTitle: "Neighbors",
    createdAt: "2021-01-19",
    likeCount: 60,
    viewCount: 94,
    commentCount: 95,
    accessStatus: "viewer",
    ownerId: 0,
    ownerName: "Leupold Gillon",
    sharedUsers: [],
    categories: [],
  },
  {
    noteId: 22,
    dataUrl: "http://chicagotribune.com",
    noteTitle: "Love Is a Woman (Death Is a Woman)",
    createdAt: "2020-09-29",
    likeCount: 43,
    viewCount: 66,
    commentCount: 63,
    accessStatus: "owner",
    ownerId: 104,
    ownerName: "Livvyy Williams",
    sharedUsers: [],
    categories: [],
  },
  {
    noteId: 21,
    dataUrl: "http://google.es",
    noteTitle: "How to Lose Friends & Alienate People",
    createdAt: "2020-09-28",
    likeCount: 56,
    viewCount: 81,
    commentCount: 73,
    accessStatus: "editor",
    ownerId: 4,
    ownerName: "Jordana Stanwix",
    sharedUsers: [],
    categories: [],
  },
  {
    noteId: 15,
    dataUrl: "http://dell.com",
    noteTitle: "Blind Chance (Przypadek)",
    createdAt: "2020-12-24",
    likeCount: 72,
    viewCount: 0,
    commentCount: 48,
    accessStatus: "viewer",
    ownerId: 27,
    ownerName: "Florance Collen",
    sharedUsers: [],
    categories: [],
  },
  {
    noteId: 26,
    dataUrl: "http://weebly.com",
    noteTitle: "I Think I Do",
    createdAt: "2020-10-15",
    likeCount: 96,
    viewCount: 84,
    commentCount: 94,
    accessStatus: "owner",
    ownerId: 104,
    ownerName: "Nataline Crab",
    sharedUsers: [],
    categories: [],
  },
  {
    noteId: 14,
    dataUrl: "http://is.gd",
    noteTitle: "Fox and His Friends (Faustrecht der Freiheit)",
    createdAt: "2020-12-04",
    likeCount: 69,
    viewCount: 13,
    commentCount: 22,
    accessStatus: "editor",
    ownerId: 9,
    ownerName: "Orelie Sybe",
    sharedUsers: [],
    categories: [],
  },
  {
    noteId: 10,
    dataUrl: "https://livejournal.com",
    noteTitle: "First Position",
    createdAt: "2020-11-27",
    likeCount: 56,
    viewCount: 56,
    commentCount: 33,
    accessStatus: "viewer",
    ownerId: 5,
    ownerName: "Lolly Eck",
    sharedUsers: [],
    categories: [],
  },
  {
    noteId: 29,
    dataUrl: "http://artisteer.com",
    noteTitle: "Pauline at the Beach (Pauline à la Plage)",
    createdAt: "2021-04-18",
    likeCount: 31,
    viewCount: 87,
    commentCount: 10,
    accessStatus: "owner",
    ownerId: 104,
    ownerName: "Sinclair Bogue",
    sharedUsers: [],
    categories: [],
  },
  {
    noteId: 11,
    dataUrl: "https://eepurl.com",
    noteTitle: "I'm Gonna Git You Sucka",
    createdAt: "2021-09-10",
    likeCount: 78,
    viewCount: 87,
    commentCount: 72,
    accessStatus: "editor",
    ownerId: 7,
    ownerName: "Linnea Brussels",
    sharedUsers: [],
    categories: [],
  },
  {
    noteId: 3,
    dataUrl: "https://imdb.com",
    noteTitle: "Hello Herman",
    createdAt: "2020-11-09",
    likeCount: 87,
    viewCount: 54,
    commentCount: 5,
    accessStatus: "viewer",
    ownerId: 25,
    ownerName: "Charisse Joisce",
    sharedUsers: [],
    categories: [],
  },
  {
    noteId: 1,
    dataUrl: "http://europa.eu",
    noteTitle: "Mulholland Falls",
    createdAt: "2021-07-06",
    likeCount: 16,
    viewCount: 9,
    commentCount: 39,
    accessStatus: "owner",
    ownerId: 104,
    ownerName: "Elvis Krugmann",
    sharedUsers: [],
    categories: [],
  },
];

export const sharedUsers = [
  { userId: 104, firstName: "Brian", lastName: "Yin" },
  { userId: 102, firstName: "Boquan", lastName: "Yin" },
  { userId: 103, firstName: "Toubat", lastName: "Brian" },
  { userId: 105, firstName: "Lucheng", lastName: "Qing" },
];

export const categories = [
  "Physics",
  "Math",
  "Computer Science",
  "Chemistry",
  "Computer Engineering",
  "Statistics",
  "Machine Learning",
  "General",
  "Jasd JAsda asd",
  "Lorem Aasd Jasd",
  "Asd Asd",
];

export const communityNotes = [];
