const path = require("path");
const express = require("express");
const cors = require("cors");
const morgan = require("morgan");

const app = express();

app.use(
  cors({
    origin: "http://localhost:8080",
  })
);

// logging in Apache combined standard
app.use(morgan("combined"));

// recognize the incoming Request Object as a JSON Object.
app.use(express.json()); 

// parse requests of content-type - application/x-www-form-urlencoded
// Hugh:  bodyParser is deprecated, not implemented yet 
//app.use(bodyParser.urlencoded({ extended: true }));


// The build folder for storing static files generated by Vue
app.use(express.static(path.join(__dirname, "..", "public")));

// simple route
app.get("/*", (req, res) => {
  res.json({ message: "Welcome to bezkoder application." });
});

app.post("/status", (req, res) => {
  console.log(req.body);
  res.json({ message: `${req.body.name} ASDASDADADASD` });
});

module.exports = app;